language: java
sudo: false
install: true

jdk:
- oraclejdk8

jobs:
  include:
    - stage: compile
      script: ./gradlew classes
    - stage: test
      script: ./gradlew test

stages:
  - compile
  - test
