/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ExampleTest {
    @Test public void testExampleMethod() {
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
